[run]
language = "python"
entrypoint = "app.py"
encoding = "utf8"
exec = "python3 app.py"

[environment]
FLASK_APP = "app.py"
FLASK_ENV = "development"
FLASK_DEBUG = "True"
HOST = "0.0.0.0"
PORT = "5000"

[workflow.btec_app]
defaultBranch = "main"
run = "python app.py"
id = "btec_app"
language = "Python"
type = "browser"
onBoot = false